[build]
    command = 'pnpm run build'
    functions = "functions"
    publish = "dist"

[[redirect]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[dev]
    targetPort = 4173

